termine/announce.go
=> termine: Make announce utf-8 safe

www/stammtisch_weiszer_stein.md
I'm unsure what to write. They don't have much vegetarian food. I'm especially unsure about the last sentence, we could omit that as well. They no longer have Macs and as far as I know they are a completely different restaurant under the same name and the same location.
=> Update description of "Weißer Stein"

data/data.go
Database column info_url is wrong, the column is called infourl
=> fix typo in data.go

data/data.go
Fixes:
mero@eris ~$ bin/termine password 287                      
Kann Vortrag nicht lesen: sql: expected 7 destination arguments in Scan, not 6
=> Scan into Abstract too

www/cryptoparty.html
forgot to add this in the last PR
=> "Technik für Nichttechniker" added to cryptoparty website

www/_includes/termine.md, www/howtotreff.md
siehe https://twitter.com/JackMcCrack/status/801381718225723392
Hab auch nen Moment gebraucht, den einen Ort zu finden wo es steht ;)
=> Add start time in more places

www/yarpnarp.md
Gäste kriegen das auf der Mailingliste ja nicht mit…
=> Noch mehr Warnungen über Stammtischverlegungen

www/howtotreff.md, www/verbrauch.md
Dies wurde auf den entsprechenden Seiten vermerkt. Dieser Commit kann
zurückgenommen (reverted) werden, sobald der Graph wieder funktioniert.
=> Zur Zeit funktioniert der Graph nicht.

www/kontakt.md
=> Fix missed mailman links related to commit 879cfd3

c14h/main.go
=> don't accept c14h on stammtisch-dates

Dockerfile, README.md, build_website.sh, entrypoint.sh, nnev-website-nginx.conf, nnev-website-supervisor.conf
=> Dockerize website build

www/pizza.md
This reverts commit b3bfdf083f7702abca3821776614161ddd112766.
=> Revert "Pizza außer Betrieb"

www/index.md
To make the main page more friendly to new people, we should add a section clarifying our approach there.
=> Add section Neugierig to main page

www/_layouts/stammtisch.html
gemäß https://www.vrn.de/service/entwickler/auskunft/index.html aktualisiert
=> Korrigierter VRN Link

www/stammtisch_medocs.md
see https://github.com/nnev/website/commit/63540ea70bd18a721af5743d9d1e73f04c891523\#diff-45f92ef7696001132491d5eaf9cd84ffR12
layout checked using local jekyll instance
=> Fix Medocs entry

www/anfahrt.md, www/index.md
=> Revert "Add note regarding room change"

www/index.md
This reverts commit 63c79214ba9038a7132ba09e0e2be5b9e670987b.
=> Revert "2023-04-20 Raumänderung"

www/index.md
This reverts commit 59f33d4d35c3d2085726a74fef14c6ae56d10c55.
=> Revert "Add note 2023-10-12"

www/howtotreff.md, www/index.md
The referenced university page is not a thing anymore.
=> remove reference to covid-19 regulations

www/index.md
Dafür existiert "termine override".
This reverts commit f11a7ee1180542d741000b04008c2d7716af6f0a.
=> Revert "Kein Stammtisch weil MRMCD"
